### ISSUE TITLE
docs.bigbluebutton.org still shows v2.2

### ISSUE THREAD

**Issue by fireba11** [bigbluebutton/bigbluebutton.github.io#251]
The new v2.3 got released a couple days ago, and since 2.2 is based on ubuntu 16.04 which is EOL there will probably never be another bugfix release for it. Hence 2.3 should move from 2.3-dev to default and get some upgrade guide (or advise to backup greenlight DB if in use and recordings and do a clean install ...).
It's likely someone is already working on this but since there was no issue tracking progress ...

**Comment by ffdixon** [comment]
I'm working on it!  There will be an update to the docs within the next day or two.

**Comment by mk-hs** [comment]
The install link in the footer of bigbluebutton.org is still pointing to 2.2 as well, perhaps you can switch it to 2.3 once it's ready :)

**Comment by antobinary** [comment]
>The install link in the footer of bigbluebutton.org is still pointing to 2.2 as well, perhaps you can switch it to 2.3 once it's ready :)

Thanks for pointing this out! Looks like Fred has fixed this since!

I did some work on the docs the last two days and I think this issue can be now closed. I am opening a few additional issues to update specific parts of pages.
Please open issues or send PRs if you encounter spots that still need updating or are missing altogether!
